hardware:
    left_front_led:
        type: GratbotLED
        red_pin:   15
        green_pin: 16
        blue_pin:  18
    right_front_led:
        type: GratbotLED
        red_pin:   19
        green_pin: 21
        blue_pin:  22
    wheel_turn_servo:
        type: GratbotServo
        max_right_steps: 280
        max_left_steps: 500
        servo_number: 2
    camera_yaw_servo:
        type: GratbotServo
        max_right_steps: 280
        max_left_steps: 500
        servo_number: 0
    camera_pitch_servo:
        type: GratbotServo
        max_right_steps: 280
        max_left_steps: 500
        servo_number: 1
    wheel_motor:
        type: GratbotMotor
        motor_pin_en: 11
        motor_pin_1: 13
        motor_pin_2: 12
    left_ir_sensor:
        type: GratbotIRSensor
        pin: 38
    middle_ir_sensor:
        type: GratbotIRSensor
        pin: 36
    right_ir_sensor:
        type: GratbotIRSensor
        pin: 35

