hardware:
    left_front_hip:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 350
        scale_ratio: 1
        servo_number: 0
    left_front_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 1
        servo_number: 1
    left_middle_hip:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 350
        scale_ratio: 1
        servo_number: 2
    left_middle_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 1
        servo_number: 3
    left_back_hip:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 350
        scale_ratio: 1
        servo_number: 4
    left_back_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 1
        servo_number: 5
    right_back_hip:
        type: GratbotServo
        min_steps: 250
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 6
    right_back_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 7
    right_middle_hip:
        type: GratbotServo
        min_steps: 250
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 8
    right_middle_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 9
    right_front_hip:
        type: GratbotServo
        min_steps: 250
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 10
    right_front_knee:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 11
    leg_controller:
        type: LegControl
        period_seconds: 5
        cadences:
          tapping:
            right_front_knee:
              times: [0,0.5,0.6,0.9,1.0]
              positions: [0, 0, -100,-100,0 ]
            left_middle_knee:
              times: [0,0.5,0.6,0.9,1.0]
              positions: [0, 0, -100,-100,0 ]
            right_back_knee:
              times: [0,0.5,0.6,0.9,1.0]
              positions: [0, 0, -100,-100,0 ]
