hardware:
    left_front_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 0
    left_front_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 1
    left_middle_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 2
    left_middle_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 3
    left_back_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 4
    left_back_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 5
    right_back_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 6
    right_back_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 7
    right_middle_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 8
    right_middle_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 9
    right_front_hip:
        type: GratbotServo
        max_right_steps: 200
        neutral_steps: 300
        max_left_steps: 350
        servo_number: 10
    right_front_knee:
        type: GratbotServo
        max_right_steps: 150
        neutral_steps: 300
        max_left_steps: 400
        servo_number: 11
