hardware:
    camera_x:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 100
        servo_number: 12
    camera_y:
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 100
        servo_number: 13
    left_front_hip: &left_hip_servo
        type: GratbotServo
        min_steps: 200
        neutral_steps: 300
        max_steps: 350
        scale_ratio: 1
        servo_number: 0
    left_front_knee: &left_knee_servo
        type: GratbotServo
        min_steps: 120
        neutral_steps: 300
        max_steps: 400
        scale_ratio: 1
        servo_number: 1
    left_middle_hip:
        <<: *left_hip_servo
        servo_number: 2
    left_middle_knee:
        <<: *left_knee_servo
        servo_number: 3
    left_back_hip:
        <<: *left_hip_servo
        servo_number: 4
    left_back_knee:
        <<: *left_knee_servo
        servo_number: 5
    right_back_hip: &right_hip_servo
        type: GratbotServo
        min_steps: 250
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 6
    right_back_knee: &right_knee_servo
        type: GratbotServo
        min_steps: 120
        neutral_steps: 300
        max_steps: 400
        scale_ratio: -1
        servo_number: 7
    right_middle_hip:
        <<: *right_hip_servo
        servo_number: 8
    right_middle_knee:
        <<: *right_knee_servo
        servo_number: 9
    right_front_hip:
        <<: *right_hip_servo
        servo_number: 10
    right_front_knee:
        <<: *right_knee_servo
        servo_number: 11
    leg_controller:
        type: LegControl
        period_seconds: 1.0
        left_knee_cadence:
            left_front_knee: &tripod_gait_knee_set_1
              times: [0,0.25,0.5,0.75,1.0]
              positions: [0,-50,0,0,0]
            left_middle_knee: &tripod_gait_knee_set_2
              times: [0,0.25,0.5,0.75,1.0]
              positions: [0,0,0,-50,0]
            left_back_knee: *tripod_gait_knee_set_1
        left_hip_cadence:
            left_front_hip: &tripod_gait_hip_set_1
              times: [0,0.25,0.5,0.75,1.0]
              positions: [-40,0,40,0,-40]
            left_middle_hip: &tripod_gait_hip_set_2
              times: [0,0.25,0.5,0.75,1.0]
              positions: [40,0,-40,0,40]
            left_back_hip: *tripod_gait_knee_set_1
        right_hip_cadence:
            right_front_hip: *tripod_gait_hip_set_2
            right_middle_hip: *tripod_gait_hip_set_1
            right_back_hip: *tripod_gait_hip_set_2
        right_knee_cadence:
            right_front_knee: *tripod_gait_knee_set_2
            right_middle_knee: *tripod_gait_knee_set_1
            right_back_knee: *tripod_gait_knee_set_2
    wave_paw:
        type: LegControl
        period_seconds: 2.0
        left_knee_cadence:
            left_front_knee: 
              times: [0,0.5,1.0]
              positions: [-180,-50,-180]
            left_middle_knee: &no_action_set
              times: [0,1.0]
              positions: [0,0]
            left_back_knee: *no_action_set
        left_hip_cadence:
            left_front_hip: 
              times: [0,0.5,1.0]
              positions: [+50,+50,+50]
            left_middle_hip: *no_action_set
            left_back_hip: *no_action_set
        right_hip_cadence:
            right_front_hip: *no_action_set
            right_middle_hip: *no_action_set
            right_back_hip: *no_action_set
        right_knee_cadence:
            right_front_knee: *no_action_set
            right_middle_knee: *no_action_set
            right_back_knee: *no_action_set
    legs_idle:
        type: LegControl
        period_seconds: 10.0
        left_knee_cadence:
            left_front_knee: *no_action_set
            left_middle_knee: *no_action_set
            left_back_knee: *no_action_set
        left_hip_cadence:
            left_front_hip: *no_action_set
            left_middle_hip: *no_action_set
            left_back_hip: *no_action_set
        right_hip_cadence:
            right_front_hip: *no_action_set
            right_middle_hip: *no_action_set
            right_back_hip: *no_action_set
        right_knee_cadence:
            right_front_knee: *no_action_set
            right_middle_knee: *no_action_set
            right_back_knee: *no_action_set

